; ============================================================================
; kos_fs_rom.asm — k/OS Phase 16: ROM disk block-layer backend
; ============================================================================
; Date:    6 May 2026
; Status:  Phase 16 Part 1 — block layer + format
; Revision: r1 — 6 May 2026 — initial. Provides _BlockReadROM, the ROM
;               disk's read-only side of the FS storage abstraction.
;               Called via per-volume function pointer in the volume table.
;               The ROM disk has no _BlockWriteROM — the volume table's
;               write pointer is null for A:, and sys_write rejects
;               with ERR_READONLY before reaching the block layer.
;
; Purpose: Translate sector/buffer requests into word reads from the ROM
;            disk image into the caller's buffer.
;
; ROM disk layout (compile-time fixed):
;   Pages    : $FC..$FD (2 pages = 128 KB)
;   Sectors  : 0..255 (256 sectors of 512 bytes)
;   Generated by external 'mkromdisk' tool, packed into ROM at $FC0000.
;
; Sector → page/offset math (identical to RAM disk, simpler bounds):
;   page    = ROMDISK_PAGE_BASE + (sector >> 7)        ; sector / 128
;   offset  = (sector & $7F) << 9                       ; (sector % 128) * 512
;
; Both operations identical to the RAM-disk math in kos_fs_ram.asm; we
; could share _SectorToAddr code with a base-page parameter, but the
; saved space (maybe 8 words) is not worth the extra parameter-passing
; overhead. Each backend keeps its own translator.
;
; --- ABI -------------------------------------------------------------------
;
; _BlockReadROM:
;   In:   D0  = sector number (word, 0..255)
;         XY0 = destination buffer (24-bit), 512 bytes will be written
;   Out:  C   = 0 on success
;         C   = 1 with D0 = ERR_IO if sector ≥ ROMDISK_SECTORS
;   Clobbers: D0, D1, D2, X0, X1, flags
;   Preserves: D3, Y0, Y1 (after the call), XY2, XY3
;
; ============================================================================

;-----------------------------------------------------------------------------
; _ROMSectorToAddr — internal helper
;
;   In:   D0  = sector number (word)
;   Out:  C=0: XY1 = (page : byte_offset_within_page)
;              D0  = ERR_OK
;         C=1: D0  = ERR_IO (sector out of range)
;   Clobbers: D0, D1, XY1, flags
;
; Note: no host branch — ROM disk is fixed-size on every target.
;-----------------------------------------------------------------------------
_ROMSectorToAddr:
                ; --- Bounds check ---------------------------------------
                CMP     D0, #ROMDISK_SECTORS
                BHS     .out_of_range

                ; D0 = sector. Compute:
                ;   Y1 = ROMDISK_PAGE_BASE + (sector >> 7)
                ;   X1 = (sector & $7F) << 9

                ; --- Page byte: D1 = (sector >> 7) + base ---------------
                MOVE    D1, D0                  ; D1 = sector copy
                SHL     D1                      ; D1 = sector << 1
                HIGH    D1                      ; D1 = sector >> 7
                ADD     D1, #ROMDISK_PAGE_BASE  ; D1 = base + (sector >> 7)
                MOVE    Y1, D1

                ; --- Byte offset: X1 = (sector & $7F) << 9 --------------
                AND     D0, #$7F                ; D0 = sector mod 128
                SWAPB   D0                      ; D0 = (sector mod 128) << 8
                SHL     D0                      ; D0 = (sector mod 128) << 9
                MOVE    X1, D0

                LOADI   D0, #ERR_OK
                RETCC

.out_of_range:
                LOADI   D0, #ERR_IO
                RETCS


;-----------------------------------------------------------------------------
; _BlockReadROM
;
; Read one 512-byte sector from the ROM disk into the caller's buffer.
;-----------------------------------------------------------------------------
_BlockReadROM:
                ; Translate sector → XY1 = source ROM-disk address.
                ; XY0 already holds the destination from caller.
                CALLR   _ROMSectorToAddr
                BCS     .read_err

                ; --- Copy 256 words: [XY1] → [XY0] ----------------------
                LOADI   D2, #256                ; word counter

.read_loop:
                LOADD   D0, [XY1]+              ; 2 cyc
                STORED  D0, [XY0]+              ; 2 cyc
                SUB     D2, #1                  ; 3 cyc — sets Z for branch
                BNE     .read_loop              ; 3 cyc taken

                LOADI   D0, #ERR_OK
                CLC
.read_err:
                ; D0 = ERR_IO, C=1 from _ROMSectorToAddr — fall through.
                RET

; ============================================================================
; End of kos_fs_rom.asm
; ============================================================================
