#!/usr/bin/env python3
# iigs_fon_to_k16.py -- Apple IIGS QuickDraw font ($C8 .FON) -> K16 KGFX .inc.
# Emits the gfx_font_defs.inc layout (descriptor + glyph bits + wtab/otab),
# matching pcface_to_k16.py / spleen_bdf_to_k16.py output.
#   * <=8px cell  -> narrow byte/row (.BYTE, MSB=col0)
#   * >8px cell   -> wide  word/row (.WORD, bit15=col0)   [needs the >8px path]
# Proportional always: w[c]=advance (owTable width), o[c]=bearing (owTable offset,
# signed). Glyph image = strike cols loc[i]..loc[i+1] (ink box), left-justified.
import sys

def parse_fon(b):
    def w(o): return b[o]|b[o+1]<<8
    def sw(o):
        v=w(o); return v-0x10000 if v&0x8000 else v
    namelen=b[0]; name=b[1:1+namelen].decode('mac-roman','replace'); h=1+namelen
    mf=h+w(h)*2
    F=dict(firstChar=w(mf+2),lastChar=w(mf+4),widMax=w(mf+6),kernMax=sw(mf+8),fRectWidth=w(mf+12),
           fRectHeight=w(mf+14),owTLoc=w(mf+16),ascent=w(mf+18),descent=w(mf+20),
           leading=w(mf+22),rowWords=w(mf+24),size=w(h+6),name=name)
    img=mf+26; stride=F['rowWords']*2; nrows=F['fRectHeight']
    nloc=F['lastChar']-F['firstChar']+3
    loc_off=img+stride*nrows; ow_off=(mf+16)+F['owTLoc']*2
    loc=[w(loc_off+2*i) for i in range(nloc)]
    ow =[(b[ow_off+2*i],b[ow_off+2*i+1]) for i in range(nloc)]  # (advance, bearing)
    F.update(img=img,stride=stride,loc=loc,ow=ow,bytes=b)
    return F

def glyph_rows(F,ch,cellw):
    """Return (rows, advance, bearing, imgW). rows: cellw-wide bit ints, MSB=col0."""
    b=F['bytes']; i=ch-F['firstChar']; loc=F['loc']; ow=F['ow']
    adv,owoff=ow[i]
    missing=(adv==0xFF and owoff==0xFF)
    x0,x1=loc[i],loc[i+1]; imgW=x1-x0
    nrows=F['fRectHeight']
    rows=[]
    top=15 if cellw>8 else 7                    # storage-unit MSB = col0
    for r in range(nrows):
        v=0
        if not missing:
            for k in range(min(imgW, top+1)):    # clamp to storage width (clip rightmost)
                c=x0+k
                o=F['img']+r*F['stride']+(c>>3)
                if (b[o]>>(7-(c&7)))&1:
                    v|=1<<(top-k)               # top-justify to bit15 (wide)/bit7 (narrow)
        rows.append(v)
    if missing:
        adv=ow[F['lastChar']-F['firstChar']+1][0]  # missing-symbol advance
        if adv==0xFF: adv=cellw
        bear=0; imgW=0
    else:
        bear=owoff+F['kernMax']                     # true left bearing = owOffset biased by kernMax
    return rows,adv&0xFF,bear,imgW

def measure(F,first,last):
    mw=0
    for ch in range(first,last+1):
        i=ch-F['firstChar']
        if 0<=i<len(F['loc'])-1:
            adv,bear=F['ow'][i]
            if not (adv==0xFF and bear==0xFF):
                mw=max(mw,F['loc'][i+1]-F['loc'][i])
    return mw

def emit(F,first,last,label,src_note,cap=16):
    n=last-first+1
    cellw=measure(F,first,last)
    clipped=[]
    if cellw>cap:
        clipped=[ch for ch in range(first,last+1)
                 if (F['ow'][ch-F['firstChar']]!=(0xFF,0xFF)) and
                    (F['loc'][ch-F['firstChar']+1]-F['loc'][ch-F['firstChar']])>cap]
        cellw=cap
    wide=cellw>8
    H=F['fRectHeight']
    glyphs=[];wtab=[];otab=[]
    for ch in range(first,last+1):
        rows,adv,bear,imgW=glyph_rows(F,ch,cellw)
        glyphs.append(rows);wtab.append(adv);otab.append(bear&0xFF)
    gbytes=n*H*(2 if wide else 1)
    L=[]
    L.append("; "+"="*76)
    L.append(f"; {label}.inc -- ASCII {first}..{last} ({'PROPORTIONAL' if True else ''}, "
             f"{cellw}x{H} {'word/row' if wide else 'byte/row'}), generated.")
    L.append("; "+"-"*76)
    L.append(f";   {src_note}")
    L.append(f"; Generated by iigs_fon_to_k16.py. cell {cellw}x{H}, "
             f"{'bit15' if wide else 'bit7'}=leftmost. WTAB/OTAB .BYTE arrays indexed by")
    L.append(f"; (c-FNT_FIRST), byte-offset from {label}_bits. Patch FNT_BITS_PG/OF at")
    L.append(f"; runtime with LEA {label}_bits.")
    if clipped: L.append(f"; WARNING: {len(clipped)} glyph(s) wider than {cap}px clipped: {clipped}")
    L.append("; "+"="*76)
    L.append("")
    L.append(f"font_{label}:")
    L.append(f"                .WORD   {first}             ; FNT_FIRST")
    L.append(f"                .WORD   {last}            ; FNT_LAST")
    L.append(f"                .WORD   {cellw}              ; FNT_WIDTH (cell cols)")
    L.append(f"                .WORD   {H}              ; FNT_HEIGHT")
    L.append(f"                .WORD   {F['widMax']}              ; FNT_ADVANCE (mono fallback)")
    L.append(f"                .WORD   {F['ascent']}              ; FNT_ASCENT")
    L.append(f"                .WORD   $0001           ; FNT_FLAGS (FNT_FL_PROP)")
    L.append(f"                .WORD   0               ; FNT_BITS_PG (patched at runtime)")
    L.append(f"                .WORD   0               ; FNT_BITS_OF (patched at runtime)")
    L.append(f"                .WORD   {gbytes}            ; FNT_WTAB (bytes from glyph bits)")
    L.append(f"                .WORD   {gbytes+n}            ; FNT_OTAB")
    L.append("")
    L.append(f"{label}_bits:")
    for idx,ch in enumerate(range(first,last+1)):
        rows=glyphs[idx]
        if wide:
            cells=", ".join(f"${r&0xFFFF:04X}" for r in rows)
            fmt=".WORD "
        else:
            cells=", ".join(f"${r&0xFF:02X}" for r in rows)
            fmt=".BYTE "
        disp="SP" if ch==32 else (chr(ch) if 33<=ch<=126 else f"#{ch}")
        L.append(f"                {fmt}  {cells}   ; {disp} ({ch}) w={wtab[idx]} o={otab[idx]-256 if otab[idx]>=128 else otab[idx]}")
    L.append(f"                ; glyph table = {gbytes} bytes")
    L.append("")
    L.append(f"{label}_wtab:")
    for i in range(0,n,16):
        L.append("                .BYTE   "+", ".join(f"${x:02X}" for x in wtab[i:i+16]))
    L.append(f"                ; wtab = {n} bytes")
    L.append("")
    L.append(f"{label}_otab:")
    for i in range(0,n,16):
        L.append("                .BYTE   "+", ".join(f"${x:02X}" for x in otab[i:i+16]))
    L.append(f"                ; otab = {n} bytes")
    return "\n".join(L)+"\n", dict(cellw=cellw,wide=wide,H=H,n=n,clipped=clipped)

if __name__=="__main__":
    path=sys.argv[1]; label=sys.argv[2]
    first=int(sys.argv[3]) if len(sys.argv)>3 else 32
    last=int(sys.argv[4]) if len(sys.argv)>4 else 127
    F=parse_fon(open(path,"rb").read())
    note=f"Source: Apple IIGS {F['name']} {F['size']}pt (QuickDraw font, public archive)."
    txt,meta=emit(F,first,last,label,note)
    sys.stderr.write(f"{label}: cell {meta['cellw']}x{meta['H']} {'WIDE' if meta['wide'] else 'narrow'} "
                     f"n={meta['n']} clipped={len(meta['clipped'])}\n")
    sys.stdout.write(txt)
