#!/usr/bin/env python3
# pcface_to_k16.py -- convert a pcface fontmap.js into a K16 font include.
#
# Source: https://github.com/susam/pcface  (ModernDOS 8x16 = CC0 / public domain)
# fontmap.js lines look like:
#   'A': [0x00, 0x00, ... 16 bytes ...], // [A] (65)
# where the trailing (N) is the CP437 code position. Bytes are one row each,
# MSB = leftmost pixel -- a 1:1 match for gfx_font.asm's renderer.
#
# Emits a contiguous glyph table for codes FIRST..LAST plus the K16 font
# descriptor, in the gfx_font_defs.inc layout. BITS pointer is left $0000;
# the harness patches it at runtime with `LEA <bits_label>` (as the demo does).
#
# PROPORTIONAL (F4): pass `prop` to emit a proportional strike instead of mono.
# Each glyph is LEFT-JUSTIFIED in the fixed 8-wide cell (row << lo); advance
# w[c] = ink_width + track, bearing o[c] = 0 (non-negative -> opaque proportional
# works). FNT_FLAGS bit0 (FNT_FL_PROP) is set; FNT_WTAB/FNT_OTAB are byte offsets
# from the glyph-bitmap base; two .BYTE tables (width, signed offset) indexed by
# (c-FIRST) are emitted after the bitmap, read bytewise by LOADB in _fn_setup.
#
# Usage: pcface_to_k16.py fontmap.js out.inc [FIRST] [LAST] [prop] [track] [space]
#   e.g.  pcface_to_k16.py fontmap.js gfx_font_ascii.inc          # mono
#         pcface_to_k16.py fontmap.js gfx_font_ascii_prop.inc 32 127 prop

import re, sys

GLYPH_BYTES = 16
CELL_WIDTH  = 8

# ---- proportional analysis (F4) -------------------------------------------
def measure_glyph(rows):
    """Returns (lo, hi, ink_width); blank glyph -> (None, None, 0). col0 = MSB."""
    occ = 0
    for r in rows:
        occ |= (r & 0xFF)
    if occ == 0:
        return None, None, 0
    lo = hi = None
    for col in range(CELL_WIDTH):
        if occ & (0x80 >> col):
            if lo is None:
                lo = col
            hi = col
    return lo, hi, (hi - lo + 1)

def left_justify(rows, lo):
    if not lo:
        return list(rows)
    return [((r << lo) & 0xFF) for r in rows]

def build_prop(ordered, track, space_width):
    """ordered: list of row-lists in code order. -> (just_rows, wtab, otab)."""
    just, wtab, otab = [], [], []
    for rows in ordered:
        lo, hi, ink = measure_glyph(rows)
        if ink == 0:
            just.append(list(rows)); wtab.append(space_width & 0xFF); otab.append(0)
        else:
            just.append(left_justify(rows, lo)); wtab.append((ink + track) & 0xFF); otab.append(0)
    return just, wtab, otab

# ---- emit ------------------------------------------------------------------
def main():
    src, out = sys.argv[1], sys.argv[2]
    first = int(sys.argv[3]) if len(sys.argv) > 3 else 32
    last  = int(sys.argv[4]) if len(sys.argv) > 4 else 127
    prop  = (len(sys.argv) > 5 and sys.argv[5].lower() == 'prop')
    track = int(sys.argv[6]) if len(sys.argv) > 6 else 1
    space = int(sys.argv[7]) if len(sys.argv) > 7 else 4

    pat = re.compile(r'\[((?:0x[0-9a-fA-F]{2}\s*,?\s*){16})\].*?\((\d+)\)')
    glyphs = {}
    for line in open(src, encoding='utf-8'):
        m = pat.search(line)
        if not m:
            continue
        rows = [int(b, 16) for b in re.findall(r'0x([0-9a-fA-F]{2})', m.group(1))]
        if len(rows) == 16:
            glyphs[int(m.group(2))] = rows

    missing = [c for c in range(first, last + 1) if c not in glyphs]
    if missing:
        sys.exit(f"missing glyphs for codes: {missing}")

    desc_label = "font_ascii"
    bits_label = "ascii_glyph_bits"
    n = last - first + 1
    ordered = [glyphs[c] for c in range(first, last + 1)]

    if prop:
        rows_out, wtab, otab = build_prop(ordered, track, space)
        flags    = "$0001           ; FNT_FLAGS (FNT_FL_PROP)"
        bitmap_b = n * GLYPH_BYTES
        wtab_off = f"{bitmap_b}            ; FNT_WTAB (bytes from glyph bits)"
        otab_off = f"{bitmap_b + n}            ; FNT_OTAB"
    else:
        rows_out = ordered
        flags    = "0               ; FNT_FLAGS"
        wtab_off = "0               ; FNT_WTAB (0 = monospace)"
        otab_off = "0               ; FNT_OTAB"

    L = []
    L.append("; ============================================================================")
    kind = "PROPORTIONAL" if prop else "monospace"
    L.append(f"; {out.split('/')[-1]} -- ASCII {first}..{last} ({kind}, 8x16), generated.")
    L.append("; ----------------------------------------------------------------------------")
    L.append("; Source: pcface ModernDOS 8x16 -- CC0 / public domain (no attribution req'd).")
    L.append(";   https://github.com/susam/pcface  ::  src/font/moderndos/LICENSE.txt")
    L.append("; Generated by pcface_to_k16.py. One byte/row, MSB = leftmost pixel.")
    if prop:
        L.append(f"; Proportional: left-justified cell, advance w[c]=ink+{track}, bearing o[c]=0,")
        L.append(f";   space={space}px. WTAB/OTAB are .BYTE arrays indexed by (c-FNT_FIRST),")
        L.append(";   byte-offset from ascii_glyph_bits; read bytewise by _fn_setup.")
    L.append("; DATA ONLY -- include in a harness body (after a hold, before code includes).")
    L.append(f"; Patch {desc_label} FNT_BITS_PG/OF at runtime with LEA {bits_label}.")
    L.append("; ============================================================================")
    L.append("")
    L.append(f"{desc_label}:")
    L.append(f"                .WORD   {first}             ; FNT_FIRST")
    L.append(f"                .WORD   {last}            ; FNT_LAST")
    L.append( "                .WORD   8               ; FNT_WIDTH")
    L.append( "                .WORD   16              ; FNT_HEIGHT")
    L.append( "                .WORD   8               ; FNT_ADVANCE")
    L.append( "                .WORD   13              ; FNT_ASCENT")
    L.append(f"                .WORD   {flags}")
    L.append( "                .WORD   0               ; FNT_BITS_PG (patched at runtime)")
    L.append( "                .WORD   0               ; FNT_BITS_OF (patched at runtime)")
    L.append(f"                .WORD   {wtab_off}")
    L.append(f"                .WORD   {otab_off}")
    L.append("")
    L.append(f"{bits_label}:")
    for i, c in enumerate(range(first, last + 1)):
        row = ", ".join(f"${b:02X}" for b in rows_out[i])
        disp = "SP" if c == 32 else (chr(c) if 33 <= c <= 126 else f"#{c}")
        suffix = f"  w={wtab[i]}" if prop else ""
        L.append(f"                .BYTE   {row}   ; {disp} ({c}){suffix}")
    L.append(f"                ; glyph table = {n * GLYPH_BYTES} bytes")
    L.append("")

    if prop:
        L.append("ascii_wtab:")
        for i in range(0, n, 16):
            L.append("                .BYTE   " + ", ".join(f"${b:02X}" for b in wtab[i:i+16]))
        L.append(f"                ; wtab = {n} bytes")
        L.append("")
        L.append("ascii_otab:")
        for i in range(0, n, 16):
            L.append("                .BYTE   " + ", ".join(f"${b:02X}" for b in otab[i:i+16]))
        L.append(f"                ; otab = {n} bytes")
        L.append("")

    open(out, "w").write("\n".join(L))
    extra = " proportional" if prop else ""
    print(f"wrote {out}: codes {first}..{last} ({n} glyphs, "
          f"{n*GLYPH_BYTES} bytes{extra})")

if __name__ == "__main__":
    main()
