#!/usr/bin/env python3
# ----------------------------------------------------------------------------
# pcface_prop.py -- proportional-strike additions for pcface_to_k16.py (F4).
#
# The three functions below (measure_glyph / left_justify / emit_prop_inc) are
# the drop-in for the converter: feed them the per-glyph 16-byte row lists the
# converter already builds. This standalone wrapper parses an existing mono
# *_ascii.inc so the logic can be run + verified now; in the converter, skip
# the parse and call left_justify/measure_glyph straight off the glyph list.
#
# Strike model (auto PC conversion): glyphs are LEFT-JUSTIFIED in the fixed
# 8-wide cell (row << lo), advance w[c] = ink_width + track, bearing o[c] = 0.
# Non-negative bearing => opaque proportional is correct (bg cell at pen covers
# the ink). FNT_FLAGS bit0 (FNT_FL_PROP) set; FNT_WTAB/FNT_OTAB are byte
# offsets from the glyph-bitmap base (matches gfx_setfont's bits_base + off).
# Tables are .BYTE arrays indexed by (c - FNT_FIRST), read bytewise by LOADB.
# ----------------------------------------------------------------------------
import re
import sys

GLYPH_BYTES = 16            # fixed cell, 1 byte/row, MSB = leftmost
CELL_WIDTH  = 8

def measure_glyph(rows):
    """rows: list of GLYPH_BYTES ints (0..255), MSB=col0.
    Returns (lo, hi, ink_width). Blank glyph -> (None, None, 0)."""
    occ = 0
    for r in rows:
        occ |= (r & 0xFF)
    if occ == 0:
        return None, None, 0
    lo = None
    hi = None
    for col in range(CELL_WIDTH):          # col 0 = bit7 (MSB = leftmost)
        if occ & (0x80 >> col):
            if lo is None:
                lo = col
            hi = col
    return lo, hi, (hi - lo + 1)

def left_justify(rows, lo):
    """Shift every row left so ink column `lo` lands at cell col 0."""
    if lo is None or lo == 0:
        return list(rows)
    return [((r << lo) & 0xFF) for r in rows]

def build_prop(glyphs, track=1, space_width=4):
    """glyphs: list of (char, rows). Returns (just_glyphs, wtab, otab).
    just_glyphs: left-justified row lists; wtab/otab: per-glyph byte values."""
    just, wtab, otab = [], [], []
    for ch, rows in glyphs:
        lo, hi, ink = measure_glyph(rows)
        if ink == 0:                        # blank (space) -> fixed advance
            just.append(list(rows))
            wtab.append(space_width & 0xFF)
            otab.append(0)
        else:
            just.append(left_justify(rows, lo))
            wtab.append((ink + track) & 0xFF)
            otab.append(0)                  # left-justified -> zero bearing
    return just, wtab, otab

# ---- emit -----------------------------------------------------------------
def _byte_rows(label, byte_lists, comment_fn):
    out = [f"{label}:"]
    for i, bl in enumerate(byte_lists):
        cells = ", ".join(f"${b:02X}" for b in bl)
        out.append(f"                .BYTE   {cells}   ; {comment_fn(i)}")
    return out

def emit_prop_inc(first, last, height, ascent, glyphs,
                  track=1, space_width=4, src_note=""):
    n = last - first + 1
    assert len(glyphs) == n, f"glyph count {len(glyphs)} != range {n}"
    just, wtab, otab = build_prop(glyphs, track, space_width)
    bitmap_bytes = n * GLYPH_BYTES
    wtab_off = bitmap_bytes              # bits-relative (gfx_setfont: bits + off)
    otab_off = bitmap_bytes + n

    def gly_cmt(i):
        c = first + i
        nm = chr(c) if 33 <= c <= 126 else ("SP" if c == 32 else f"#{c}")
        return f"{nm} ({c})  w={wtab[i]}"

    L = []
    L.append("; " + "=" * 76)
    L.append("; gfx_font_ascii_prop.inc -- ASCII 32..127 (8x16) PROPORTIONAL, generated.")
    L.append("; " + "-" * 76)
    if src_note:
        L.append(f";   {src_note}")
    L.append("; Generated by pcface_to_k16.py (F4 proportional: left-justified cell,")
    L.append(f";   advance w[c]=ink+{track}, bearing o[c]=0, space={space_width}px).")
    L.append("; One byte/row, MSB = leftmost. WTAB/OTAB are .BYTE arrays indexed by")
    L.append("; (c-FNT_FIRST), offset from ascii_glyph_bits. Patch FNT_BITS_PG/OF at")
    L.append("; runtime with LEA ascii_glyph_bits.")
    L.append("; " + "=" * 76)
    L.append("")
    L.append("font_ascii:")
    L.append(f"                .WORD   {first}             ; FNT_FIRST")
    L.append(f"                .WORD   {last}            ; FNT_LAST")
    L.append(f"                .WORD   {CELL_WIDTH}               ; FNT_WIDTH (cell cols scanned)")
    L.append(f"                .WORD   {height}              ; FNT_HEIGHT")
    L.append(f"                .WORD   {CELL_WIDTH}               ; FNT_ADVANCE (mono fallback)")
    L.append(f"                .WORD   {ascent}              ; FNT_ASCENT")
    L.append(f"                .WORD   $0001           ; FNT_FLAGS (FNT_FL_PROP)")
    L.append(f"                .WORD   0               ; FNT_BITS_PG (patched at runtime)")
    L.append(f"                .WORD   0               ; FNT_BITS_OF (patched at runtime)")
    L.append(f"                .WORD   {wtab_off}            ; FNT_WTAB (bytes from glyph bits)")
    L.append(f"                .WORD   {otab_off}            ; FNT_OTAB")
    L.append("")
    L += _byte_rows("ascii_glyph_bits", just, gly_cmt)
    L.append(f"                ; glyph table = {bitmap_bytes} bytes")
    L.append("")
    # width table
    L.append("ascii_wtab:")
    for i in range(0, n, 16):
        chunk = wtab[i:i+16]
        cells = ", ".join(f"${b:02X}" for b in chunk)
        L.append(f"                .BYTE   {cells}")
    L.append(f"                ; wtab = {n} bytes")
    L.append("")
    # offset table
    L.append("ascii_otab:")
    for i in range(0, n, 16):
        chunk = otab[i:i+16]
        cells = ", ".join(f"${b:02X}" for b in chunk)
        L.append(f"                .BYTE   {cells}")
    L.append(f"                ; otab = {n} bytes")
    return "\n".join(L) + "\n"

# ---- standalone proof: parse an existing mono inc, emit the prop inc --------
def parse_mono_inc(text):
    first = int(re.search(r"\.WORD\s+(\d+)\s*;\s*FNT_FIRST", text).group(1))
    last  = int(re.search(r"\.WORD\s+(\d+)\s*;\s*FNT_LAST",  text).group(1))
    height= int(re.search(r"\.WORD\s+(\d+)\s*;\s*FNT_HEIGHT",text).group(1))
    ascent= int(re.search(r"\.WORD\s+(\d+)\s*;\s*FNT_ASCENT",text).group(1))
    src   = re.search(r";\s*Source:.*", text)
    src_note = src.group(0).lstrip("; ").rstrip() if src else ""
    # glyph rows: each .BYTE line in the bitmap = one 16-byte glyph
    rows = []
    for m in re.finditer(r"\.BYTE\s+((?:\$[0-9A-Fa-f]{2}\s*,?\s*){16})\s*;", text):
        bs = [int(x, 16) for x in re.findall(r"\$([0-9A-Fa-f]{2})", m.group(1))]
        rows.append(bs)
    n = last - first + 1
    rows = rows[:n]
    glyphs = [(first + i, rows[i]) for i in range(n)]
    return first, last, height, ascent, glyphs, src_note

if __name__ == "__main__":
    inp = sys.argv[1] if len(sys.argv) > 1 else "gfx_font_ascii.inc"
    out = sys.argv[2] if len(sys.argv) > 2 else "gfx_font_ascii_prop.inc"
    with open(inp) as f:
        text = f.read()
    first, last, height, ascent, glyphs, src_note = parse_mono_inc(text)
    blob = emit_prop_inc(first, last, height, ascent, glyphs,
                         track=1, space_width=4, src_note=src_note)
    with open(out, "w") as f:
        f.write(blob)
    # quick summary to stderr
    _, wtab, _ = build_prop(glyphs, 1, 4)
    sample = {chr(c): wtab[c - first] for c in (ord(' '), ord('i'), ord('l'),
              ord('m'), ord('W'), ord('A'), ord('.'))}
    sys.stderr.write(f"wrote {out}: {last-first+1} glyphs; sample widths {sample}\n")
